# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 12:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_lahir', models.DateField()),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('alamat', models.CharField(max_length=200)),
                ('kode_pos', models.CharField(max_length=6)),
                ('desa', models.CharField(max_length=150)),
                ('kecamatan', models.CharField(max_length=150)),
                ('kabupaten', models.CharField(max_length=150)),
                ('provinsi', models.CharField(max_length=150)),
                ('negara', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('self_introduction', models.TextField()),
                ('website', models.URLField()),
                ('bahasa', models.CharField(max_length=150)),
                ('keahlian', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
