# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-08 13:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profil.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, upload_to=profil.models.upload_location)),
                ('tgl_lahir', models.DateField()),
                ('jenis_kelamin', models.CharField(choices=[('Pria', 'Pria'), ('Wanita', 'Wanita')], max_length=12)),
                ('self_introduction', models.TextField()),
                ('alamat', models.CharField(max_length=200)),
                ('kode_pos', models.CharField(max_length=6)),
                ('desa', models.CharField(max_length=150)),
                ('kecamatan', models.CharField(max_length=150)),
                ('kabupaten', models.CharField(max_length=150)),
                ('provinsi', models.CharField(max_length=150)),
                ('negara', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('website', models.URLField(blank=True)),
                ('fb', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('googleplus', models.URLField(blank=True)),
                ('statuspekerja', models.CharField(blank=True, choices=[('Bukan Pekerja', 'Bukan Pekerja'), ('Pekerja', 'Pekerja')], default='Bukan Pekerja', max_length=24)),
                ('bahasa', models.CharField(choices=[('Bahasa Indonesia', 'Bahasa Indonesia'), ('English', 'English'), ('Other', 'Other')], max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
