# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='jenis_kelamin',
            field=models.CharField(choices=[('Pria', 'Pria'), ('Wanita', 'Wanita')], max_length=12),
        ),
    ]
