# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_auto_20170103_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='upload'),
        ),
    ]
