# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0003_profil_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
    ]
