# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-07 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0005_auto_20170107_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='fb',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='googleplus',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='hobi',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profil',
            name='status_pekerja',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profil',
            name='twitter',
            field=models.URLField(blank=True),
        ),
    ]
