# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-08 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(max_length=254)),
                ('k_slug', models.SlugField(blank=True)),
            ],
        ),
    ]
