# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-08 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kategori', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategori',
            name='k_slug',
            field=models.SlugField(blank=True),
        ),
    ]
