# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-19 13:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kategori', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jasa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_jasa', models.CharField(max_length=150)),
                ('alamat', models.CharField(max_length=200)),
                ('kode_pos', models.CharField(max_length=6)),
                ('desa', models.CharField(max_length=150)),
                ('kecamatan', models.CharField(max_length=150)),
                ('kabupaten', models.CharField(max_length=150)),
                ('provinsi', models.CharField(max_length=150)),
                ('negara', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('website', models.URLField(blank=True)),
                ('fb', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('googleplus', models.URLField(blank=True)),
                ('terima_panggilan', models.CharField(choices=[('tidak', 'Tidak'), ('ya', 'Ya')], max_length=15)),
                ('peringkat', models.CharField(choices=[('1', 'Kurang'), ('2', 'Biasa '), ('3', 'Baik'), ('4', 'Cukup Baik'), ('5', 'Super')], max_length=15)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kategori_jasa', to='kategori.Kategori')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pemilik', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
