# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-19 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jasa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jasa',
            name='peringkat',
            field=models.CharField(blank=True, choices=[('1', 'Kurang'), ('2', 'Biasa '), ('3', 'Baik'), ('4', 'Cukup Baik'), ('5', 'Super')], max_length=15),
        ),
        migrations.AlterField(
            model_name='jasa',
            name='terima_panggilan',
            field=models.CharField(blank=True, choices=[('tidak', 'Tidak'), ('ya', 'Ya')], default='tidak', max_length=15),
        ),
    ]
