# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-20 04:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jasa', '0002_auto_20170219_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jasa',
            name='peringkat',
        ),
    ]
