# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-20 04:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jasa', '0003_remove_jasa_peringkat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jasa',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kategori.Kategori'),
        ),
        migrations.AlterField(
            model_name='jasa',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
