# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-20 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kategori', '0001_initial'),
        ('jasa', '0004_auto_20170220_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jasa',
            name='kategori',
        ),
        migrations.AddField(
            model_name='jasa',
            name='kategori',
            field=models.ManyToManyField(to='kategori.Kategori'),
        ),
    ]
