# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-08 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jasa', '0005_auto_20170220_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='jasa',
            name='nj_slug',
            field=models.SlugField(blank=True),
        ),
    ]
